name: Slack Notification Workflow

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        with:
          text: "A pull request has been made in the repository ${{ github.repository }}. Action: ${{ github.event.action }}. Author: ${{ github.actor }}."
          channel: "	k200229 Shoaib Ahmed"  
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
