name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or whichever version you're using

      - name: Install dependencies
        run: npm install

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Update dependencies
        run: npm update

      - name: Create Pull Request
        run: |
          git config --global user.name 'Mortiest Morty'
          git config --global user.email 'shoaib.sohoo123@gmail.com'
          git checkout -b update-dependencies
          git add package.json package-lock.json
          git commit -m "Update dependencies"
          git push origin update-dependencies
          # Use GitHub API or `hub` to create pull request here

      - name: Run tests
        run: npm test
