name: Documentation Deployment

on:
  push:
    paths:
      - 'documentation/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build Documentation
        run: mkdocs build

      - name: List Output Files
        run: ls -lah ./site

      - name: Archive Site Directory
        run: tar -czvf site_archive.tar.gz ./site

      - name: Upload Site as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: site_archive.tar.gz

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUB_TOKEN }}
          publish_dir: ./site
